"""Add file_url to quotes

Revision ID: 0fc3a23902c7
Revises: 8957c3971604
Create Date: 2026-02-21 01:42:21.172283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc3a23902c7'
down_revision: Union[str, None] = '8957c3971604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'file_url')
    # ### end Alembic commands ###
