"""add_subcategory_id_to_provider_services

Revision ID: 1e77342ea0ae
Revises: f9f35be947a1
Create Date: 2026-02-23 17:19:37.254424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e77342ea0ae'
down_revision: Union[str, None] = 'f9f35be947a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activity_notes_event_id', table_name='activity_notes')
    op.create_index(op.f('ix_activity_notes_id'), 'activity_notes', ['id'], unique=False)
    op.add_column('provider_services', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.alter_column('provider_services', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'provider_services', 'subcategories', ['subcategory_id'], ['id'])
    op.drop_index('idx_service_payments_service', table_name='service_payments')
    op.create_index(op.f('ix_service_payments_id'), 'service_payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_payments_id'), table_name='service_payments')
    op.create_index('idx_service_payments_service', 'service_payments', ['provider_service_id'], unique=False)
    op.drop_constraint(None, 'provider_services', type_='foreignkey')
    op.alter_column('provider_services', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('provider_services', 'subcategory_id')
    op.drop_index(op.f('ix_activity_notes_id'), table_name='activity_notes')
    op.create_index('idx_activity_notes_event_id', 'activity_notes', ['event_id'], unique=False)
    # ### end Alembic commands ###
