"""add_arca_integration

Revision ID: 371385748361
Revises: c5d38e9aeb69
Create Date: 2026-03-02 01:44:10.744465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371385748361'
down_revision: Union[str, None] = 'c5d38e9aeb69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arca_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuit', sa.String(), nullable=False),
    sa.Column('razon_social', sa.String(), nullable=False),
    sa.Column('condicion_iva', sa.Integer(), nullable=True),
    sa.Column('punto_vta', sa.Integer(), nullable=False),
    sa.Column('domicilio_comercial', sa.String(), nullable=True),
    sa.Column('inicio_actividades', sa.Date(), nullable=True),
    sa.Column('cert_path', sa.String(), nullable=True),
    sa.Column('key_path', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arca_config_id'), 'arca_config', ['id'], unique=False)
    op.create_table('invoice_iva_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('iva_id', sa.Integer(), nullable=False),
    sa.Column('base_imp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('importe', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_iva_items_id'), 'invoice_iva_items', ['id'], unique=False)
    op.add_column('invoices', sa.Column('arca_cbte_tipo', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('arca_punto_vta', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('arca_cbte_nro', sa.BigInteger(), nullable=True))
    op.add_column('invoices', sa.Column('arca_concepto', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('arca_tipo_doc_receptor', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('arca_nro_doc_receptor', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('arca_condicion_iva_receptor', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('cae', sa.String(length=14), nullable=True))
    op.add_column('invoices', sa.Column('cae_vto', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('arca_result', sa.String(length=1), nullable=True))
    op.add_column('invoices', sa.Column('arca_obs', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('imp_neto', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('imp_iva', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('imp_tot_conc', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('imp_op_ex', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('imp_trib', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('mon_id', sa.String(length=3), nullable=True))
    op.add_column('invoices', sa.Column('mon_cotiz', sa.Numeric(precision=12, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'mon_cotiz')
    op.drop_column('invoices', 'mon_id')
    op.drop_column('invoices', 'imp_trib')
    op.drop_column('invoices', 'imp_op_ex')
    op.drop_column('invoices', 'imp_tot_conc')
    op.drop_column('invoices', 'imp_iva')
    op.drop_column('invoices', 'imp_neto')
    op.drop_column('invoices', 'arca_obs')
    op.drop_column('invoices', 'arca_result')
    op.drop_column('invoices', 'cae_vto')
    op.drop_column('invoices', 'cae')
    op.drop_column('invoices', 'arca_condicion_iva_receptor')
    op.drop_column('invoices', 'arca_nro_doc_receptor')
    op.drop_column('invoices', 'arca_tipo_doc_receptor')
    op.drop_column('invoices', 'arca_concepto')
    op.drop_column('invoices', 'arca_cbte_nro')
    op.drop_column('invoices', 'arca_punto_vta')
    op.drop_column('invoices', 'arca_cbte_tipo')
    op.drop_index(op.f('ix_invoice_iva_items_id'), table_name='invoice_iva_items')
    op.drop_table('invoice_iva_items')
    op.drop_index(op.f('ix_arca_config_id'), table_name='arca_config')
    op.drop_table('arca_config')
    # ### end Alembic commands ###
