"""add_code_to_categories

Revision ID: 39563962b958
Revises: 450e6ae297c6
Create Date: 2026-02-22 21:22:00.262377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39563962b958'
down_revision: Union[str, None] = '450e6ae297c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('code', sa.String(), nullable=True))
    op.create_index(op.f('ix_categories_code'), 'categories', ['code'], unique=False)
    op.add_column('families', sa.Column('code', sa.String(), nullable=True))
    op.create_index(op.f('ix_families_code'), 'families', ['code'], unique=False)
    op.add_column('subcategories', sa.Column('code', sa.String(), nullable=True))
    op.create_index(op.f('ix_subcategories_code'), 'subcategories', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcategories_code'), table_name='subcategories')
    op.drop_column('subcategories', 'code')
    op.drop_index(op.f('ix_families_code'), table_name='families')
    op.drop_column('families', 'code')
    op.drop_index(op.f('ix_categories_code'), table_name='categories')
    op.drop_column('categories', 'code')
    # ### end Alembic commands ###
