"""add_trade_name_to_clients

Revision ID: 3e2d17bf953a
Revises: f9199771e8e0
Create Date: 2026-02-22 22:28:47.502531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2d17bf953a'
down_revision: Union[str, None] = 'f9199771e8e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('trade_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_clients_trade_name'), 'clients', ['trade_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_trade_name'), table_name='clients')
    op.drop_column('clients', 'trade_name')
    # ### end Alembic commands ###
