"""add_tax_condition_to_clients

Revision ID: 3e4f0482cea4
Revises: 3e2d17bf953a
Create Date: 2026-02-22 22:53:38.519694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4f0482cea4'
down_revision: Union[str, None] = '3e2d17bf953a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('tax_condition', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'tax_condition')
    # ### end Alembic commands ###
