"""add_notes_table

Revision ID: 3ebec826ec93
Revises: 7451b23b8005
Create Date: 2026-03-04 17:52:55.641194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ebec826ec93'
down_revision: Union[str, None] = '7451b23b8005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_entity_id'), 'notes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_notes_entity_type'), 'notes', ['entity_type'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.drop_index('ix_exchange_rates_date', table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_index('idx_wa_messages_chat_id', table_name='wa_messages')
    op.drop_index('idx_wa_messages_timestamp', table_name='wa_messages')
    op.drop_table('wa_messages')
    op.drop_table('invoice_audit_logs')
    op.drop_index('idx_wa_conversations_last_msg', table_name='wa_conversations')
    op.drop_table('wa_conversations')
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.alter_column('invoices', 'cbte_asoc_tipo',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('invoices', 'cbte_asoc_pto_vta',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('invoices', 'cbte_asoc_nro',
               existing_type=sa.VARCHAR(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('service_payments', 'currency',
               existing_type=sa.VARCHAR(length=5),
               nullable=False,
               existing_server_default=sa.text("'USD'::character varying"))
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.alter_column('service_payments', 'currency',
               existing_type=sa.VARCHAR(length=5),
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('invoices', 'cbte_asoc_nro',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('invoices', 'cbte_asoc_pto_vta',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('invoices', 'cbte_asoc_tipo',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.create_table('wa_conversations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('wa_conversations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_group', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('profile_pic_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('unread_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wa_conversations_pkey'),
    sa.UniqueConstraint('chat_id', name='wa_conversations_chat_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_wa_conversations_last_msg', 'wa_conversations', [sa.text('last_message_at DESC NULLS LAST')], unique=False)
    op.create_table('invoice_audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('old_value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=100), server_default=sa.text("'Sistema'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='invoice_audit_logs_invoice_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='invoice_audit_logs_pkey')
    )
    op.create_table('wa_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chat_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('wa_message_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('from_me', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('sender_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('media_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['wa_conversations.id'], name='wa_messages_conversation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='wa_messages_pkey')
    )
    op.create_index('idx_wa_messages_timestamp', 'wa_messages', ['timestamp'], unique=False)
    op.create_index('idx_wa_messages_chat_id', 'wa_messages', ['chat_id'], unique=False)
    op.create_table('exchange_rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=5), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False),
    sa.Column('buy_rate', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('sell_rate', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='exchange_rates_pkey')
    )
    op.create_index('ix_exchange_rates_date', 'exchange_rates', ['date'], unique=False)
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_entity_type'), table_name='notes')
    op.drop_index(op.f('ix_notes_entity_id'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
