"""add category and family to products

Revision ID: 67b07bb95051
Revises: d3821e454966
Create Date: 2026-02-22 20:23:26.859720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b07bb95051'
down_revision: Union[str, None] = 'd3821e454966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('family', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'family')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
