"""add_currency_to_models

Revision ID: 68b063be7baf
Revises: 6d12c192d1b9
Create Date: 2026-02-21 00:01:41.197144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b063be7baf'
down_revision: Union[str, None] = '6d12c192d1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_services', sa.Column('currency', sa.String(), server_default='ARS', nullable=False))
    op.add_column('invoices', sa.Column('currency', sa.String(), server_default='ARS', nullable=False))
    op.add_column('products', sa.Column('currency', sa.String(), server_default='ARS', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'currency')
    op.drop_column('invoices', 'currency')
    op.drop_column('client_services', 'currency')
    # ### end Alembic commands ###
