"""Add client_id and contact_id to CalendarEvent

Revision ID: 6d12c192d1b9
Revises: 979ae2c79e9d
Create Date: 2026-02-20 20:03:35.214059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d12c192d1b9'
down_revision: Union[str, None] = '979ae2c79e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('calendar_events', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calendar_events', 'contacts', ['contact_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'calendar_events', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_column('calendar_events', 'contact_id')
    op.drop_column('calendar_events', 'client_id')
    # ### end Alembic commands ###
