"""add_quote_id_to_invoices

Revision ID: 6f72300cf49a
Revises: 371385748361
Create Date: 2026-03-02 12:32:01.458571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f72300cf49a'
down_revision: Union[str, None] = '371385748361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('quote_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'quotes', ['quote_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'quote_id')
    # ### end Alembic commands ###
