"""Add color_code to InvoiceStatus and ON DELETE SET NULL to status_id and invoices FKs

Revision ID: 785b4c7f727f
Revises: c3badb8a57f5
Create Date: 2026-02-20 16:38:46.845362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785b4c7f727f'
down_revision: Union[str, None] = 'c3badb8a57f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_statuses', sa.Column('color_code', sa.String(), nullable=True))
    op.drop_constraint('invoices_status_id_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_provider_id_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_client_id_fkey', 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'invoice_statuses', ['status_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'invoices', 'providers', ['provider_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'invoices', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_client_id_fkey', 'invoices', 'clients', ['client_id'], ['id'])
    op.create_foreign_key('invoices_provider_id_fkey', 'invoices', 'providers', ['provider_id'], ['id'])
    op.create_foreign_key('invoices_status_id_fkey', 'invoices', 'invoice_statuses', ['status_id'], ['id'])
    op.drop_column('invoice_statuses', 'color_code')
    # ### end Alembic commands ###
