"""add_website_and_lead_id_to_calendar

Revision ID: 7f3c7fe2d8d6
Revises: d65add3f9ba8
Create Date: 2026-02-23 10:33:14.471094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3c7fe2d8d6'
down_revision: Union[str, None] = 'd65add3f9ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calendar_events', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
    op.add_column('clients', sa.Column('website', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'website')
    op.drop_column('clients', 'website')
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_column('calendar_events', 'lead_id')
    # ### end Alembic commands ###
