"""replace_subcategory_id_with_product_id

Revision ID: c5d38e9aeb69
Revises: 1e77342ea0ae
Create Date: 2026-02-23 17:52:25.461966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d38e9aeb69'
down_revision: Union[str, None] = '1e77342ea0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_services', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint('provider_services_subcategory_id_fkey', 'provider_services', type_='foreignkey')
    op.create_foreign_key(None, 'provider_services', 'products', ['product_id'], ['id'])
    op.drop_column('provider_services', 'subcategory_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_services', sa.Column('subcategory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'provider_services', type_='foreignkey')
    op.create_foreign_key('provider_services_subcategory_id_fkey', 'provider_services', 'subcategories', ['subcategory_id'], ['id'])
    op.drop_column('provider_services', 'product_id')
    # ### end Alembic commands ###
