"""add subcategory to products

Revision ID: d1db027da563
Revises: 67b07bb95051
Create Date: 2026-02-22 20:31:04.612512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1db027da563'
down_revision: Union[str, None] = '67b07bb95051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('subcategory', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'subcategory')
    # ### end Alembic commands ###
