"""add_dashboard_configs_table

Revision ID: d3821e454966
Revises: 0fc3a23902c7
Create Date: 2026-02-22 16:03:02.685964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3821e454966'
down_revision: Union[str, None] = '0fc3a23902c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('widgets', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_configs_id'), 'dashboard_configs', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_configs_user_id'), 'dashboard_configs', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_configs_user_id'), table_name='dashboard_configs')
    op.drop_index(op.f('ix_dashboard_configs_id'), table_name='dashboard_configs')
    op.drop_table('dashboard_configs')
    # ### end Alembic commands ###
