"""add_address_fields_to_leads

Revision ID: f9f35be947a1
Revises: 7f3c7fe2d8d6
Create Date: 2026-02-23 10:42:23.325861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f35be947a1'
down_revision: Union[str, None] = '7f3c7fe2d8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('address', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('city', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('province', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'country')
    op.drop_column('leads', 'province')
    op.drop_column('leads', 'city')
    op.drop_column('leads', 'address')
    # ### end Alembic commands ###
